version: 0.2

phases:
  pre_build:
    commands:
      - echo mvn version
      - mvn -version
      - docker version
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/spring-boot-rest-example-0.5.0.war
  discard-paths: yes